version: "3.9"

services:
  app:
    depends_on:
      - db
    image: hub.aiursoft.com/aiursoft/wechatexam:latest
    volumes:
      - wechatexam-aspnet:/data/.aspnet/
      - wechatexam-files:/data/files
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=mth;Uid=mth;Pwd=<mth_password>;
      - ConnectionStrings__DbType=MySql
      - Storage__Path=/data/files
      - AppSettings__AuthProvider=OIDC
      - AppSettings__OIDC__Authority=https://auth.aiursoft.com/application/o/we-chat-exam
      - AppSettings__OIDC__ClientId={{WCE_CLIENT_ID}}
      - AppSettings__OIDC__ClientSecret={{WCE_CLIENT_SECRET}}
      - AppSettings__Wechat__AppId={{WCEXAM_APP_ID}}
      - AppSettings__Wechat__AppSecret={{WCEXAM_APP_SECRET}}
      - OpenAI__CompletionApiUrl=https://ollama.aiursoft.com/api/chat
      - OpenAI__Model=qwen3:30b-a3b-instruct-2507-q8_0
      - OpenAI__Token={{OLLAMA_GATEWAY_API_KEY}}
    networks:
      - proxy_app
      - internal
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
      update_config:
        order: stop-first
        delay: 60s

  db:
    image: hub.aiursoft.com/mysql
    volumes:
      - wechatexam-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=mth
      - MYSQL_USER=mth
      - MYSQL_PASSWORD=<mth_password>
    networks:
      - internal
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
      update_config:
        order: stop-first
        delay: 60s

volumes:
  wechatexam-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/wechatexam-data/files
  wechatexam-aspnet:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/wechatexam-data/aspnet
  wechatexam-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/wechatexam-data/mysql

networks:
  proxy_app:
    external: true
  internal:
    driver: overlay