version: "3.9"

services:
  app:
    depends_on:
      - db
    image: hub.aiursoft.com/aiursoft/warp:latest
    volumes:
      - warp-aspnet:/data/.aspnet/
      - warp-files:/data/files
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=warp;Uid=warp;Pwd=<warp_password>;
      - ConnectionStrings__DbType=MySql
      - Storage__Path=/data/files
      - AppSettings__AuthProvider=OIDC
      - AppSettings__OIDC__Authority=https://auth.aiursoft.com/application/o/warp
      - AppSettings__OIDC__ClientId={{WARP_CLIENT_ID}}
      - AppSettings__OIDC__ClientSecret={{WARP_CLIENT_SECRET}}
    networks:
      - proxy_app
      - internal
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
      update_config:
        order: stop-first
        delay: 60s

  db:
    image: hub.aiursoft.com/mysql
    volumes:
      - warp-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=warp
      - MYSQL_USER=warp
      - MYSQL_PASSWORD=<warp_password>
    networks:
      - internal
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
      update_config:
        order: stop-first
        delay: 60s

volumes:
  warp-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/warp-data/files
  warp-aspnet:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/warp-data/aspnet
  warp-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/warp-data/mysql

networks:
  proxy_app:
    external: true
  internal:
    driver: overlay
