version: '3.9'

services:
  authentik_proxy:
    image: hub.aiursoft.com/ghcr.io/goauthentik/proxy:2025.12.1
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
        read_only: false
    environment:
      AUTHENTIK_HOST: "https://auth.aiursoft.com/"
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: "{{CLICKHOUSE_OUTPOST_TOKEN}}"
    stop_grace_period: 20s
    networks:
      - proxy_app
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
      update_config:
        order: start-first
        delay: 5s

  clickhouse:
    image: hub.aiursoft.com/clickhouse/clickhouse-server:latest
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
      - CLICKHOUSE_TELEMETRY_OPT_OUT=1 
      - CLICKHOUSE_DO_NOT_CHECK_UPDATES=1
    networks:
      - proxy_app
      - clickhouse_net
    volumes:
      - click-house-data:/var/lib/clickhouse
      - /swarm-vol/click-house/config_override.xml:/etc/clickhouse-server/config.d/config_override.xml
      - /swarm-vol/click-house/users_override.xml:/etc/clickhouse-server/users.d/users_override.xml
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
      update_config:
        order: stop-first
        delay: 60s

networks:
  clickhouse_net:
    external: true
  proxy_app:
    external: true

volumes:
  click-house-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/click-house/db-data