serverAddr = "FRP_SERVER_IP"
serverPort = 7000
auth.token = "FRP_TOKEN"
transport.poolCount = 5
transport.protocol = "quic"
transport.tcpMux = true
webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

# Check on Caddy.
[[proxies]]
name = "http"
type = "tcp"
localIP = "incoming_sites"
localPort = 80
remotePort = 80
transport.proxyProtocolVersion = "v2"
transport.useEncryption = false
transport.useCompression = true

# Check on Caddy.
[[proxies]]
name = "https"
type = "tcp"
localIP = "incoming_sites"
localPort = 443
remotePort = 443
transport.proxyProtocolVersion = "v2"
transport.useEncryption = false
transport.useCompression = true

# Regular update to ensure safe.
[[proxies]]
name = "mc"
type = "tcp"
localIP = "minecraft_server"
localPort = 25565
remotePort = 25565
transport.useEncryption = false
transport.useCompression = false

# Regular update to ensure safe.
[[proxies]]
name = "ssh_gitea"
type = "tcp"
localIP = "gitea_app"
localPort = 2201
remotePort = 2201
transport.useEncryption = false
transport.useCompression = false

# Regular update to ensure safe.
[[proxies]]
name = "ssh_gitlab"
type = "tcp"
localIP = "gitlab_gitlab"
localPort = 2202
remotePort = 2202
transport.useEncryption = false
transport.useCompression = false