version: '3.9'

services:
  app:
    image: hub.aiursoft.com/vaultwarden/server:testing
    volumes:
      - vaultwarden-data:/data/
    networks:
      - proxy_app
    environment:
      - DOMAIN=https://vault.aiursoft.com
      - SSO_ENABLED=true
      - SSO_AUTHORITY=https://auth.aiursoft.com/application/o/vaultwarden/
      - SSO_CLIENT_ID={{VAULTWARDEN_CLIENT_ID}} # e.g. vaultwarden
      - SSO_CLIENT_SECRET={{VAULTWARDEN_CLIENT_SECRET}} # e.g. supersecret
      - SSO_SCOPES="openid email profile offline_access"
      - SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION=true
      - SSO_CLIENT_CACHE_EXPIRATION=0
      - SSO_ONLY=true # Set to true to disable email+master password login and require SSO
      - SSO_SIGNUPS_MATCH_EMAIL=true # Match first SSO login to existing account by email
      - ADMIN_TOKEN={{VAULTWARDEN_ADMIN_TOKEN}} # e.g. supersecretadmintoken
      - SSO_CLIENT_CACHE_EXPIRATION=300  # 改为 5 分钟而不是 0
      - SSO_DEBUG=true  # 添加调试日志
    stop_grace_period: 60s
    deploy:
      update_config:
        order: stop-first
        delay: 60s
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.2'
          memory: 256M
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  proxy_app:
    external: true

volumes:
  vaultwarden-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/vaultwarden-data/data
