version: "3.9"

services:
  app:
    depends_on:
      - db
    image: hub.aiursoft.com/aiursoft/employeecenter:latest
    volumes:
      - employeecenter-aspnet:/data/.aspnet/
      - employeecenter-files:/data/files
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=mth;Uid=mth;Pwd=<mth_password>;
      - ConnectionStrings__DbType=MySql
      - Storage__Path=/data/files
      - AppSettings__AuthProvider=OIDC
      - AppSettings__OIDC__Authority=https://auth.aiursoft.com/application/o/employeecenter
      - AppSettings__OIDC__ClientId={{EPEC_CLIENT_ID}}
      - AppSettings__OIDC__ClientSecret={{EPEC_CLIENT_SECRET}}
    networks:
      - proxy_app
      - internal
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
      update_config:
        order: stop-first
        delay: 60s

  db:
    image: hub.aiursoft.com/mysql
    volumes:
      - employeecenter-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=mth
      - MYSQL_USER=mth
      - MYSQL_PASSWORD=<mth_password>
    networks:
      - internal
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
      update_config:
        order: stop-first
        delay: 60s

volumes:
  employeecenter-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/employeecenter-data/files
  employeecenter-aspnet:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/employeecenter-data/aspnet
  employeecenter-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/employeecenter-data/mysql

networks:
  proxy_app:
    external: true
  internal:
    driver: overlay