version: '3.9'

services:

  authentik_proxy:
    image: hub.aiursoft.com/ghcr.io/goauthentik/proxy:2025.10.1
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2147483648 # 2GB
    environment:
      AUTHENTIK_HOST: "https://auth.aiursoft.com/"
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: "{{CHARTER_OUTPOST_TOKEN}}"
    networks:
      - proxy_app
    stop_grace_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
      update_config:
        order: start-first
        delay: 5s

  app:
    image: hub.aiursoft.com/aiursoft/charter
    networks:
      - proxy_app
    stop_grace_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
      update_config:
        order: start-first
        delay: 5s

networks:
  proxy_app:
    external: true