version: '3.9'

services:
  app:
    depends_on:
      - db
    image: hub.aiursoft.com/aiursoft/aiurdrive
    volumes:
      - aiurdrive-aspnet:/data/.aspnet/
      - aiurdrive-files:/data/files
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=aiurdrive;Uid=aiurdrive;Pwd=<aiurdrive_password>;
      - ConnectionStrings__DbType=MySql
      - Storage__Path=/data/files
      - AppSettings__AuthProvider=OIDC
      - AppSettings__OIDC__Authority=https://auth.aiursoft.com/application/o/aiurdrive
      - AppSettings__OIDC__ClientId={{AIURDRIVE_CLIENT_ID}}
      - AppSettings__OIDC__ClientSecret={{AIURDRIVE_CLIENT_SECRET}}
    networks:
      - internal
      - proxy_app
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
      update_config:
        order: stop-first
        delay: 60s

  db:
    image: hub.aiursoft.com/mysql
    volumes:
      - aiurdrive-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=aiurdrive
      - MYSQL_USER=aiurdrive
      - MYSQL_PASSWORD=<aiurdrive_password>
    networks:
      - internal
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
      update_config:
        order: stop-first
        delay: 60s

volumes:
  aiurdrive-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/aiurdrive-data/files
  aiurdrive-aspnet:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/aiurdrive-data/aspnet
  aiurdrive-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/aiurdrive-data/mysql

networks:
  proxy_app:
    external: true
  internal:
    driver: overlay
