version: '3.9'

services:
  authentik_proxy:
    image: hub.aiursoft.com/ghcr.io/goauthentik/proxy:2025.10.1
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
        read_only: false
    environment:
      AUTHENTIK_HOST: "https://auth.aiursoft.com/"
      AUTHENTIK_INSECURE: "false"
      AUTHENTIK_TOKEN: "{{SAKURATRAK_OUTPOST_TOKEN}}"
    networks:
      - proxy_app
      - internal
    stop_grace_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
      update_config:
        order: start-first
        delay: 5s

  webapp:
    image: hub.aiursoft.com/edgeneko/nekoimagegallery.app
    #image: edgeneko/nekoimagegallery.app # Avoid using mirror because this app updates very frequently
    environment:
      - OVERRIDE_API_URL=https://sakuratrak.aiursoft.com/api
    networks:
      - proxy_app
      - internal
    stop_grace_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
      update_config:
        order: start-first
        delay: 5s

  server:
    image: hub.aiursoft.com/edgeneko/neko-image-gallery:edge-cpu
    #image: edgeneko/neko-image-gallery:latest-cpu # Avoid using mirror because this app updates very frequently
    networks:
      - proxy_app
      - internal
    volumes:
      - neko-image-gallery-local:/opt/NekoImageGallery/static
    depends_on:
      - qdrant_database
    environment:
      - APP_ACCESS_PROTECTED=False
      - APP_QDRANT__COLL=NekoImg-v4
      - APP_QDRANT__HOST=qdrant_database
      - APP_OCR_SEARCH__OCR_MIN_CONFIDENCE=0.05
      - APP_ADMIN_API_ENABLE=True
      - APP_STORAGE__METHOD=local
      - APP_ADMIN_TOKEN={{NEKO_IMAGE_GALLERY_ADMIN_TOKEN}}
    # runtime: nvidia
    stop_grace_period: 60s
    deploy:
      resources:
        # reservations:
        #   generic_resources:
        #     - discrete_resource_spec:
        #         kind: "NVIDIA-GPU"
        #         value: 0
        limits:
          cpus: '8.0'
          memory: 8G
      update_config:
        order: stop-first
        delay: 60s
    command: ["--root-path", "/api"]

  qdrant_database:
    image: hub.aiursoft.com/qdrant/qdrant
    networks:
      - internal
      - proxy_app
    volumes:
      - neko-image-gallery-vector-db:/qdrant/storage:z
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
      update_config:
        order: stop-first
        delay: 60s

volumes:
  neko-image-gallery-vector-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/neko-image-gallery/vector_db
  neko-image-gallery-local:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/neko-image-gallery/local_images/

networks:
  proxy_app:
    external: true
  internal:
    driver: overlay
